services:
  oracle-cdc-consumer-no-validation:
    build: .
    env_file:
      - ./env/consumer.env
    command: ["python", "app/consumer.py"]
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
      - ./state:/state
    restart: "no"

  oracle-cdc-apply-no-validation:
    build: .
    env_file:
      - ./env/consumer.env
    command: ["python", "app/apply.py"]
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
      - ./state:/state
    restart: "no"
