services:
  oracle-cdc-consumer-no-validation:
    build: .
    env_file:
      - ./env/consumer.env
    command: ["python", "-m", "app.consumer"]
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
      - ./state:/state
    restart: "no"
    networks:
      - data_platform_services
      
  oracle-cdc-apply-no-validation:
    build: .
    env_file:
      - ./env/consumer.env
    command: ["python", "-m", "app.apply"]
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
      - ./state:/state
    restart: "no"
    networks:
      - data_platform_services

networks:
  data_platform_services:
    external: true
    name: data_platform_services